var next = [
  {
    "Title": "Black Panther",
    "Year": "2018",
    "Rated": "N/A",
    "Released": "16 Feb 2018",
    "Runtime": "N/A",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Ryan Coogler",
    "Writer": "Ryan Coogler (screenplay by), Joe Robert Cole (screenplay by), Stan Lee (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by)",
    "Actors": ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o", "Danai Gurira"],
    "Plot": "T'Challa, after the death of his father, the King of Wakanda, returns home to the isolated, technologically advanced African nation to succeed to the throne and take his rightful place as king.",
    "Language": "English",
    "Country": "USA",
    "Awards": "N/A",
    "Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SX300.jpg",
    "Ratings": [],
    "Metascore": "N/A",
    "imdbRating": "N/A",
    "imdbVotes": "N/A",
    "imdbID": "tt1825683",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "N/A",
    "Production": "Marvel Studios",
    "Website": "N/A",
    "Response": "True"
  },
  {
    "Title": "Avengers: Infinity War",
    "Year": "2018",
    "Rated": "N/A",
    "Released": "04 May 2018",
    "Runtime": "N/A",
    "Genre": "Action, Adventure, Fantasy",
    "Director": "Anthony Russo, Joe Russo",
    "Writer": "Christopher Markus (screenplay), Stephen McFeely (screenplay), Stan Lee (based on the comics by), Jack Kirby (based on the comics by), Jim Starlin (comic book story), George Pérez (comic book story), Ron Lim (comic book story), Steve Ditko (characters created by: Spider-Man & Doctor Strange), Jack Kirby (character created by: Captain America), Joe Simon (character created by: Captain America), Jim Starlin (characters created by: Thanos,  Gamora & Drax)",
    "Actors": ["Karen Gillan", "Sebastian Stan", "Scarlett Johansson", "Pom Klementieff"],
    "Plot": "The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.",
    "Language": "English",
    "Country": "USA",
    "Awards": "N/A",
    "Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc0MjA1OTMxOV5BMl5BanBnXkFtZTgwMzM1NDcyNDM@._V1_SX300.jpg",
    "Ratings": [],
    "Metascore": "N/A",
    "imdbRating": "N/A",
    "imdbVotes": "N/A",
    "imdbID": "tt4154756",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "N/A",
    "Production": "Walt Disney Pictures",
    "Website": "N/A",
    "Response": "True"
  },
  {
    "Title": "Ant-Man and the Wasp",
    "Year": "2018",
    "Rated": "N/A",
    "Released": "06 Jul 2018",
    "Runtime": "N/A",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Peyton Reed",
    "Writer": "Chris McKenna (screenplay by), Erik Sommers (screenplay by), Andrew Barrer (screenplay by), Gabriel Ferrari (screenplay by), Paul Rudd (screenplay by), Stan Lee (based on the Marvel comics by), Larry Lieber (based on the Marvel comics by), Jack Kirby (based on the Marvel comics by)",
    "Actors": ["Hannah John-Kamen", "Michelle Pfeiffer", "Evangeline Lilly", "Michael Douglas"],
    "Plot": "As Scott Lang balances being both a Super Hero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past.",
    "Language": "English",
    "Country": "USA",
    "Awards": "N/A",
    "Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNWM4MWExOTUtNDk1MS00YmRhLWI0NzItZmY3MDE2ZjZkOGIwXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
    "Ratings": [],
    "Metascore": "N/A",
    "imdbRating": "N/A",
    "imdbVotes": "N/A",
    "imdbID": "tt5095030",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "N/A",
    "Production": "N/A",
    "Website": "N/A",
    "Response": "True"
  },
  {
    "Title": "Captain Marvel",
    "Year": "2019",
    "Rated": "N/A",
    "Released": "08 Mar 2019",
    "Runtime": "N/A",
    "Genre": "Action, Adventure, Sci-Fi",
    "Director": "Anna Boden, Ryan Fleck",
    "Writer": "Gene Colan (comic book by), Meg LeFauve (screenplay), Nicole Perlman (screenplay), Geneva Robertson-Dworet (screenplay), Geneva Robertson-Dworet, Roy Thomas (comic book)",
    "Actors": ["Brie Larson", "Samuel L. Jackson", "Jude Law", "Ben Mendelsohn"],
    "Plot": "The plot is unknown at this time.",
    "Language": "English",
    "Country": "USA",
    "Awards": "N/A",
    "Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ3MjIyMDQxOF5BMl5BanBnXkFtZTgwNDIxNTM2OTE@._V1_SX300.jpg",
    "Ratings": [],
    "Metascore": "N/A",
    "imdbRating": "N/A",
    "imdbVotes": "N/A",
    "imdbID": "tt4154664",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "N/A",
    "Production": "Walt Disney Pictures",
    "Website": "N/A",
    "Response": "True"
  },
  {
    "Title": "Untitled Deadpool Sequel",
    "Year": "2018",
    "Rated": "N/A",
    "Released": "18 May 2018",
    "Runtime": "N/A",
    "Genre": "Action, Adventure, Comedy",
    "Director": "David Leitch",
    "Writer": "Rob Liefeld (character), Fabian Nicieza (character), Rhett Reese (screenplay), Paul Wernick (screenplay)",
    "Actors": ["Morena Baccarin", "Ryan Reynolds", "Josh Brolin", "Brianna Hildebrand"],
    "Plot": "After surviving a near fatal knee boarding accident , a disfigured guidance counselor (Wade Wilson) struggles to fulfill his dream of becoming Poughkeepsie's most celebrated French Bulldog ...",
    "Language": "English",
    "Country": "USA",
    "Awards": "N/A",
    "Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk4OGE2Y2UtMzk2MC00OGZlLWE2NDMtNmIxYjY3M2E2MDI0XkEyXkFqcGdeQXVyNDQxNjcxNQ@@._V1_SX300.jpg",
    "Ratings": [],
    "Metascore": "N/A",
    "imdbRating": "N/A",
    "imdbVotes": "N/A",
    "imdbID": "tt5463162",
    "Type": "movie",
    "DVD": "N/A",
    "BoxOffice": "N/A",
    "Production": "Twentieth Century Fox",
    "Website": "N/A",
    "Response": "True"
  },
  {
    "Title": "Venom",
    "Year": "2018",
    "Rated": "N/A",
    "Released": "05 Oct 2018",
    "Runtime": "N/A",
    "Genre": "Action, Horror, Sci-Fi",
    "Director": "Ruben Fleischer",
    "Writer": "Kelly Marcel, Todd McFarlane (characters), David Michelinie (characters), Jeff Pinkner (screenwriter), Scott Rosenberg",
    "Actors": ["Tom Hardy", "Michelle Williams", "Woody Harrelson", "Jenny Slate"],
    "Plot": "This plot is unknown.",
    "Language": "English",
    "Country": "USA",
    "Awards": "N/A",
    "Poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BODUxNzEyNDY1NV5BMl5BanBnXkFtZTgwMjk3NDU1NDM@._V1_SX300.jpg",
    "Ratings": [],
    "Metascore": "N/A",
    "imdbRating": "N/A",
    "imdbVotes": "N/A",
    "imdbID": "tt1270797",
    "Type": "movie",
    "DVD": "18 Jun 2013",
    "BoxOffice": "N/A",
    "Production": "Columbia Pictures",
    "Website": "N/A",
    "Response": "True"
  }
]
